In [1]:
import pandas as pd

In [10]:
df = pd.read_csv('cars_data.csv')
df.head()

      brand  km_driven      fuel         owner  selling_price
0  Mahindra     163399    Diesel   First Owner         397238
1       BMW     148281       CNG   First Owner         542402
2      Fiat     182515       LPG   First Owner         539706
3    Nissan      18029       CNG  Second Owner         337551
4     Skoda     191069  Electric  Fourth Owner         217011

In [9]:
df['fuel'].value_counts()

fuel
Electric    1041
LPG         1015
Diesel      1002
Petrol       977
CNG          965
Name: count, dtype: int64

In [18]:
df['brand'].unique()

<StringArray>
[  'Mahindra',        'BMW',       'Fiat',     'Nissan',      'Skoda',
      'Volvo',     'Toyota',      'Honda',    'Hyundai',         'MG',
       'Tata',     'Maruti',     'Datsun',        'Kia',       'Jeep',
       'Ford',    'Renault',      'Isuzu',  'Chevrolet', 'Volkswagen']
Length: 20, dtype: str

In [19]:
df['fuel'].nunique()

5

In [5]:
df['owner'].value_counts()

owner
Second Owner    1275
Third Owner     1250
First Owner     1241
Fourth Owner    1234
Name: count, dtype: int64

1. One hot coding using pandas

In [8]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth Owner,owner_Second Owner,owner_Third Owner
0,Mahindra,163399,397238,False,True,False,False,False,True,False,False,False
1,BMW,148281,542402,True,False,False,False,False,True,False,False,False
2,Fiat,182515,539706,False,False,False,True,False,True,False,False,False
3,Nissan,18029,337551,True,False,False,False,False,False,False,True,False
4,Skoda,191069,217011,False,False,True,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Honda,95416,289394,False,False,False,True,False,False,True,False,False
4996,Kia,5580,488804,False,False,False,True,False,True,False,False,False
4997,Datsun,125834,314091,False,False,False,False,True,False,False,False,True
4998,Hyundai,115148,268252,False,False,True,False,False,False,False,True,False
4999,Datsun,191467,137389,False,True,False,False,False,False,False,True,False

2. k-1 OnehotEncoding

In [12]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,owner_Fourth Owner,owner_Second Owner,owner_Third Owner
0,Mahindra,163399,397238,True,False,False,False,False,False,False
1,BMW,148281,542402,False,False,False,False,False,False,False
2,Fiat,182515,539706,False,False,True,False,False,False,False
3,Nissan,18029,337551,False,False,False,False,False,True,False
4,Skoda,191069,217011,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...
4995,Honda,95416,289394,False,False,True,False,True,False,False
4996,Kia,5580,488804,False,False,True,False,False,False,False
4997,Datsun,125834,314091,False,False,False,True,False,False,True
4998,Hyundai,115148,268252,False,True,False,False,False,True,False
4999,Datsun,191467,137389,True,False,False,False,False,True,False

3. OneHotCoding using sklearn

In [15]:
from sklearn.model_selection import train_test_split

x = df[['brand','km_driven','fuel','owner']]
y = df['selling_price']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [16]:
x_train.head()

          brand  km_driven    fuel         owner
4227  Chevrolet     144154  Diesel   Third Owner
4676      Skoda     159359  Petrol  Second Owner
800         BMW      63430  Petrol  Second Owner
3671      Honda      10869     LPG  Second Owner
4193       Fiat      66001     CNG   First Owner

In [22]:
y_train.head()

4227    255180
4676    390492
800     560252
3671    103441
4193    465282
Name: selling_price, dtype: int64

In [ ]:
from sklearn.preprocessing import OneHotEncoder

from numpy import int32

ohe = OneHotEncoder(drop='first',dtype=int32)

In [24]:
ohe.fit_transform(x_train[['fuel','owner']])
ohe.fit_transform(x_test[['fuel','owner']])

<Compressed Sparse Row sparse matrix of dtype 'int32'
	with 1564 stored elements and shape (1000, 7)>

In [ ]:
x_train_new = ohe.transform(x_train[['fuel','owner']]).toarray()
x_test_new = ohe.transform(x_test[['fuel','owner']]).toarray()

x_train_new

array([[1, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4000, 7), dtype=int32)

In [31]:
x_train[['brand','km_driven']].values

array([['Chevrolet', 144154],
       ['Skoda', 159359],
       ['BMW', 63430],
       ...,
       ['Datsun', 193707],
       ['Mahindra', 140328],
       ['Nissan', 150646]], shape=(4000, 2), dtype=object)

In [38]:
import numpy as np

In [39]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Chevrolet', 144154, 1, ..., 0, 0, 1],
       ['Skoda', 159359, 0, ..., 0, 1, 0],
       ['BMW', 63430, 0, ..., 0, 1, 0],
       ...,
       ['Datsun', 193707, 1, ..., 0, 0, 1],
       ['Mahindra', 140328, 0, ..., 1, 0, 0],
       ['Nissan', 150646, 0, ..., 0, 0, 0]], shape=(4000, 9), dtype=object)

In [40]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new)).shape

(4000, 9)